In [33]:
import re
import string

import pandas as pd
import numpy as np

In [46]:
tmp = pd.read_excel("raw_data/Areas_in_blore.xlsx")
tmp.to_csv('raw_data/Areas_in_blore.csv')

# Lab Cleaning Process

## Normal cleaning

In [47]:
df = pd.read_csv("raw_data/data_file_20210527182730.csv")
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 966348799,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato/bangalore/addhuri-udupi-bho...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 990121000,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [48]:
df['address'] = df['address'].str.replace(r'['+ string.punctuation + ']'," ",)
df['reviews_list'] = df['reviews_list'].str.replace(r'['+ string.punctuation + ']'," ") # A small problem on the initial, but with more regex, can be fixed (I think :) )

/tmp/ipykernel_2301244/1931422542.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['address'] = df['address'].str.replace(r'['+ string.punctuation + ']'," ",)
/tmp/ipykernel_2301244/1931422542.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['reviews_list'] = df['reviews_list'].str.replace(r'['+ string.punctuation + ']'," ") # A small problem on the initial, but with more regex, can be fixed (I think :) )

In [49]:
df['phone'] = df['phone'].str.replace(r'[+ ]',"")

/tmp/ipykernel_2301244/272737479.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['phone'] = df['phone'].str.replace(r'[+ ]',"")

In [50]:
df[['contact number 1','contact number 2']] = df['phone'].str.split("\r\n",expand=True).fillna("No info")

In [51]:
df.isnull().sum() # Has some nulls, but all depends

url                               0
address                           0
name                              0
online_order                      0
book_table                        0
rate                           1021
votes                             0
phone                            83
location                          1
rest_type                        32
dish_liked                     4077
cuisines                          8
approx_cost(for two people)      14
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
contact number 1                  0
contact number 2                  0
dtype: int64

## Cities

**Acho que não entendi essa jossa :'(**

**Irmão, se isso for uma pegadinha eu vou ficar muito triste haha**

**Não há uma chave confiável para se fazer um de-para**

In [16]:
df_areas = pd.read_csv('raw_data/Areas_in_blore.csv')
df_areas.head()
df_areas.shape[0]

264

In [13]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),contact number 1,contact number 2
0,https://www.zomato.com/bangalore/jalsa-banasha...,942 21st Main Road 2nd Stage Banashankari ...,Jalsa,Yes,Yes,4.1/5,775,08042297555\r\n919743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Rated 4 0 RATED\n A beautiful place to ...,[],Buffet,Banashankari,08042297555,919743772233
1,https://www.zomato.com/bangalore/spice-elephan...,2nd Floor 80 Feet Road Near Big Bazaar 6th ...,Spice Elephant,Yes,No,4.1/5,787,08041714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Rated 4 0 RATED\n Had been here for din...,[],Buffet,Banashankari,08041714161,No info
2,https://www.zomato.com/SanchurroBangalore?cont...,1112 Next to KIMS Medical College 17th Cross...,San Churro Cafe,Yes,No,3.8/5,918,91966348799,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Rated 3 0 RATED\n Ambience is not that ...,[],Buffet,Banashankari,91966348799,No info
3,https://www.zomato/bangalore/addhuri-udupi-bho...,1st Floor Annakuteera 3rd Stage Banashankar...,Addhuri Udupi Bhojana,No,No,3.7/5,88,919620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Rated 4 0 RATED\n Great food and proper...,[],Buffet,Banashankari,919620009302,No info
4,https://www.zomato.com/bangalore/grand-village...,10 3rd Floor Lakshmi Associates Gandhi Baza...,Grand Village,No,No,3.8/5,166,918026612447\r\n91990121000,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Rated 4 0 RATED\n Very good restaurant ...,[],Buffet,Banashankari,918026612447,91990121000

In [15]:
df_areas['Pincode'].drop_duplicates()

0      560063
1      560007
3      560092
4      560024
5      560045
        ...
233    562157
236    562120
238    562130
240    562162
242    562125
Name: Pincode, Length: 111, dtype: int64

In [13]:
df['location'].drop_duplicates()

0                        Banashankari
4                        Basavanagudi
6                         Mysore Road
38                          Jayanagar
46                 Kumaraswamy Layout
                    ...
5736                Central Bangalore
6554                     Sanjay Nagar
6742                      Brookefield
6789       ITPL Main Road, Whitefield
6811    Varthur Main Road, Whitefield
Name: location, Length: 67, dtype: object

## My own check

In [52]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5'],
      dtype=object)

In [64]:
df['rate'] = df['rate'].str.replace('NEW','0/0')
df['rate'] = df['rate'].str.replace('-','0/0')
df['rate'] = df['rate'].fillna('0/0')

In [65]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', '0', '2.9/5', '3.5/5', '0/0', '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5'],
      dtype=object)

In [66]:
df['number_rate'] = df['rate'].apply(lambda x: str(x).split('/')[0])

In [77]:
df['number_rate'].unique()

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, nan, 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

In [76]:
df['number_rate'] = pd.to_numeric(df['number_rate'])
df['number_rate'].replace(0,np.nan,inplace=True) # Zero values can be bad to some math analyses

In [69]:
df['number_rate'].unique()

array([4.1, 3.8, 3.7, 3.6, 4.6, 4. , 4.2, 3.9, 3.1, 3. , 3.2, 3.3, 2.8,
       4.4, 4.3, 0. , 2.9, 3.5, 2.6, 3.4, 4.5, 2.5, 2.7, 4.7, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

In [70]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),contact number 1,contact number 2,number_rate
0,https://www.zomato.com/bangalore/jalsa-banasha...,942 21st Main Road 2nd Stage Banashankari ...,Jalsa,Yes,Yes,4.1/5,775,08042297555\r\n919743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Rated 4 0 RATED\n A beautiful place to ...,[],Buffet,Banashankari,08042297555,919743772233,4.1
1,https://www.zomato.com/bangalore/spice-elephan...,2nd Floor 80 Feet Road Near Big Bazaar 6th ...,Spice Elephant,Yes,No,4.1/5,787,08041714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Rated 4 0 RATED\n Had been here for din...,[],Buffet,Banashankari,08041714161,No info,4.1
2,https://www.zomato.com/SanchurroBangalore?cont...,1112 Next to KIMS Medical College 17th Cross...,San Churro Cafe,Yes,No,3.8/5,918,91966348799,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Rated 3 0 RATED\n Ambience is not that ...,[],Buffet,Banashankari,91966348799,No info,3.8
3,https://www.zomato/bangalore/addhuri-udupi-bho...,1st Floor Annakuteera 3rd Stage Banashankar...,Addhuri Udupi Bhojana,No,No,3.7/5,88,919620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Rated 4 0 RATED\n Great food and proper...,[],Buffet,Banashankari,919620009302,No info,3.7
4,https://www.zomato.com/bangalore/grand-village...,10 3rd Floor Lakshmi Associates Gandhi Baza...,Grand Village,No,No,3.8/5,166,918026612447\r\n91990121000,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Rated 4 0 RATED\n Very good restaurant ...,[],Buffet,Banashankari,918026612447,91990121000,3.8

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7379 entries, 0 to 7378
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          7379 non-null   object
 1   address                      7379 non-null   object
 2   name                         7379 non-null   object
 3   online_order                 7379 non-null   object
 4   book_table                   7379 non-null   object
 5   rate                         7379 non-null   object
 6   votes                        7379 non-null   int64
 7   phone                        7296 non-null   object
 8   location                     7378 non-null   object
 9   rest_type                    7347 non-null   object
 10  dish_liked                   3302 non-null   object
 11  cuisines                     7371 non-null   object
 12  approx_cost(for two people)  7365 non-null   object
 13  reviews_list                 7379 non-null   object
 14  menu_item                    7379 non-null   object
 15  listed_in(type)              7379 non-null   object
 16  listed_in(city)              7379 non-null   object
 17  contact number 1             7379 non-null   object
 18  contact number 2             7379 non-null   object
 19  number_rate                  7379 non-null   float64
dtypes: float64(1), int64(1), object(18)
memory usage: 1.1+ MB

#### Now, we can use the rate item to do any calc that we want.

## Testing

In [31]:
null_columns = [ c for c in df.columns if df[c].isnull().any()]

In [32]:
null_columns

['rate',
 'phone',
 'location',
 'rest_type',
 'dish_liked',
 'cuisines',
 'approx_cost(for two people)']

In [34]:
df_output_bad = df[null_columns]
df_output_bad.head()

df_output_good = df[df.columns.difference(null_columns)]
df_output_good.head()

,address,book_table,contact number 1,contact number 2,listed_in(city),listed_in(type),menu_item,name,online_order,reviews_list,url,votes
0,942 21st Main Road 2nd Stage Banashankari ...,Yes,08042297555,919743772233,Banashankari,Buffet,[],Jalsa,Yes,Rated 4 0 RATED\n A beautiful place to ...,https://www.zomato.com/bangalore/jalsa-banasha...,775
1,2nd Floor 80 Feet Road Near Big Bazaar 6th ...,No,08041714161,No info,Banashankari,Buffet,[],Spice Elephant,Yes,Rated 4 0 RATED\n Had been here for din...,https://www.zomato.com/bangalore/spice-elephan...,787
2,1112 Next to KIMS Medical College 17th Cross...,No,91966348799,No info,Banashankari,Buffet,[],San Churro Cafe,Yes,Rated 3 0 RATED\n Ambience is not that ...,https://www.zomato.com/SanchurroBangalore?cont...,918
3,1st Floor Annakuteera 3rd Stage Banashankar...,No,919620009302,No info,Banashankari,Buffet,[],Addhuri Udupi Bhojana,No,Rated 4 0 RATED\n Great food and proper...,https://www.zomato/bangalore/addhuri-udupi-bho...,88
4,10 3rd Floor Lakshmi Associates Gandhi Baza...,No,918026612447,91990121000,Banashankari,Buffet,[],Grand Village,No,Rated 4 0 RATED\n Very good restaurant ...,https://www.zomato.com/bangalore/grand-village...,166